languages:
- name: cpp
  production:
    exclude:
      - /.github/.*
      - /docs/.*
      - /examples/.*
      - /scripts/.*
      - /tests/.*
    include:
      - /src/.*
  test:
    include:
      - /tests/.*
    exclude:
      - /.github/.*
      - /docs/.*
      - /examples/.*
      - /scripts/.*
      - /tests/.*
