name: Build with Platformio

on: [push, pull_request]

jobs:
  build-for-esp8266:
    runs-on: ubuntu-latest
    container: ghcr.io/bertmelis/pio-test-container
    strategy:
      matrix:
        example: [
          examples/simple-read-VS1/simple-read-VS1.ino,
          examples/simple-read-VS2/simple-read-VS2.ino,
          examples/simple-write-VS1/simple-write-VS1.ino,
          examples/simple-write-VS2/simple-write-VS2.ino,
          examples/simple-read-GWG/simple-read-GWG.ino,
          examples/softwareserial/softwareserial.ino
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Build PlatformIO examples
        run: pio ci --lib="." --board=d1_mini
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

  build-for-esp32:
    runs-on: ubuntu-latest
    container: ghcr.io/bertmelis/pio-test-container
    strategy:
      matrix:
        example: [
          examples/generic-interface/generic-interface.ino
          examples/simple-read-VS1/simple-read-VS1.ino,
          examples/simple-read-VS2/simple-read-VS2.ino,
          examples/simple-write-VS1/simple-write-VS1.ino,
          examples/simple-write-VS2/simple-write-VS2.ino,
          examples/simple-read-GWG/simple-read-GWG.ino
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Build PlatformIO examples
        run: pio ci --lib="." --board=lolin32
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

  build-for-linux:
    runs-on: ubuntu-latest
    container: ghcr.io/bertmelis/pio-test-container
    strategy:
      matrix:
        example: [
          examples/linux/main.cpp
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Build PlatformIO examples
        run: pio ci --lib="." --project-conf="./examples/linux/platformio.ini"
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}