name: Build with Platformio

on: [push, pull_request]

jobs:
  build-for-esp8266:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
          examples/simple-read-VS1/simple-read-VS1.ino,
          examples/simple-read-VS2/simple-read-VS2.ino,
          examples/simple-write-VS1/simple-write-VS1.ino,
          examples/simple-write-VS2/simple-write-VS2.ino,
          examples/simple-read-GWG/simple-read-GWG.ino
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Download external libraries
        run: pio pkg install --global --library plerup/EspSoftwareSerial
      - name: Build PlatformIO examples
        run: pio ci --lib="." --board=d1_mini
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

  build-for-esp32:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
          examples/simple-read-VS1/simple-read-VS1.ino,
          examples/simple-read-VS2/simple-read-VS2.ino,
          examples/simple-write-VS1/simple-write-VS1.ino,
          examples/simple-write-VS2/simple-write-VS2.ino,
          examples/simple-read-GWG/simple-read-GWG.ino
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Download external libraries
        run: pio pkg install --global --library plerup/EspSoftwareSerial
      - name: Build PlatformIO examples
        run: pio ci --lib="." --board=lolin32
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

  build-for-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
          examples/linux/main.cpp
        ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Build PlatformIO examples
        run: pio ci --lib="." --project-conf="./examples/linux/platformio.ini"
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}